name: ai-quest-api-lambda tests

on:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src/ai-quest-api-lambda

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install httpx pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          pytest
